version: '3.9'

services:
  backend:
    container_name: compliance
    image: compliance
    build:
      context: .
      dockerfile: ./docker/backend/prod/Dockerfile
    entrypoint: /start.sh
    depends_on:
      compliance_database:
        condition: service_healthy
    env_file: ['./docker/backend/prod/.env']
    restart: unless-stopped
    volumes:
      - ./src:/src:rw
      - ./src/static:/var/www/html/static
      - ./src/media:/var/www/html/media
    expose:
      - 6969
    networks:
      compliance_network:
        ipv4_address: 192.168.35.3

  compliance_database:
    container_name: compliance_database
    image: postgres
    env_file: ['./docker/backend/prod/.env']
    restart: unless-stopped
    volumes:
      - backend_database:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      compliance_network:
        ipv4_address: 192.168.35.2

  nginx:
    container_name: webserver
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src/media:/var/www/html/media
      - ./src/static:/var/www/html/static
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:rw
    restart: unless-stopped
    networks:
      compliance_network:
        ipv4_address: 192.168.35.4
    ports:
      - "80:80"

volumes:
  backend_database: {}

networks:
  compliance_network:
    name: compliance_network
    ipam:
      config:
        - subnet: 192.168.35.0/20
