# Generated by Django 4.2.4 on 2023-09-04 07:45

import compliance_projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('target_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(default=compliance_projects.models.generate_uuid, null=True)),
                ('name', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('ref_code', models.CharField(max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('system_level', models.BooleanField(default=True)),
                ('category', models.TextField(default='', null=True)),
                ('subcategory', models.TextField(default='', null=True)),
                ('guidance', models.TextField(default='', null=True)),
                ('references', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operational_capability', models.TextField(default='', null=True)),
                ('control_type', models.TextField(default='', null=True)),
                ('control_domain', models.TextField(default='', null=True)),
                ('domain_name', models.TextField(default='', null=True)),
                ('dti', models.CharField(max_length=255, null=True)),
                ('dtc', models.CharField(max_length=255, null=True)),
                ('meta', models.JSONField(default=dict, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(max_length=255, null=True)),
                ('document', models.FileField(null=True, upload_to=compliance_projects.models.evidences_storage)),
                ('solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controls', models.ManyToManyField(blank=True, to='compliance_projects.control')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.complianceproject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=compliance_projects.models.generate_uuid, max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('ref_code', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('content', models.TextField(default='', null=True)),
                ('template', models.TextField(default='', null=True)),
                ('version', models.IntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('ref_code', models.CharField(max_length=255, null=True)),
                ('mitigation', models.TextField(default='', null=True)),
                ('guidance', models.TextField(default='', null=True)),
                ('meta', models.JSONField(default=dict, null=True)),
                ('implementation_group', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.control')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.evidence')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.complianceproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PolicyControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.control')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.policy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(default='', null=True)),
                ('reference_link', models.TextField(blank=True, default='', null=True)),
                ('guidance', models.TextField(blank=True, default='', null=True)),
                ('feature_evidence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controls', models.ManyToManyField(blank=True, related_name='framework_controls', to='compliance_projects.control')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_projects.framework'),
        ),
        migrations.AddField(
            model_name='control',
            name='subcontrols',
            field=models.ManyToManyField(blank=True, to='compliance_projects.subcontrol'),
        ),
        migrations.AddField(
            model_name='complianceproject',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='compliance_projects.evidence'),
        ),
        migrations.AddField(
            model_name='complianceproject',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='compliance_projects.framework'),
        ),
        migrations.AddField(
            model_name='complianceproject',
            name='policies',
            field=models.ManyToManyField(blank=True, to='compliance_projects.policy'),
        ),
        migrations.AddField(
            model_name='complianceproject',
            name='tags',
            field=models.ManyToManyField(blank=True, to='compliance_projects.complianceprojecttag'),
        ),
        migrations.AddField(
            model_name='complianceproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
