# Generated by Django 4.2.4 on 2023-09-06 08:03

import compliance_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceproject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Compliance Project', 'verbose_name_plural': 'Compliance Projects'},
        ),
        migrations.AlterModelOptions(
            name='complianceprojecttag',
            options={'ordering': ('-created_at',), 'verbose_name': 'Compliance Project Tag', 'verbose_name_plural': 'Compliance Project Tags'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ('-created_at',), 'verbose_name': 'Control', 'verbose_name_plural': 'Controls'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ('-created_at',), 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidences'},
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ('-created_at',), 'verbose_name': 'Framework', 'verbose_name_plural': 'Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('-created_at',), 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policycontrol',
            options={'ordering': ('-created_at',), 'verbose_name': 'Policy Control', 'verbose_name_plural': 'Policy Controls'},
        ),
        migrations.AlterModelOptions(
            name='projectevidence',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Evidence', 'verbose_name_plural': 'Project Evidences'},
        ),
        migrations.AlterModelOptions(
            name='subcontrol',
            options={'ordering': ('-created_at',), 'verbose_name': 'Sub Control', 'verbose_name_plural': 'Sub Controls'},
        ),
        migrations.AddField(
            model_name='complianceprojecttag',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcontrol',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='uuid',
            field=models.CharField(default=compliance_projects.models.generate_uuid, max_length=255, null=True),
        ),
    ]
