# Generated by Django 4.2.4 on 2023-09-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_projects', '0002_alter_complianceproject_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEvidence',
        ),
    ]
